travis:
  secure:
    BINSTAR_TOKEN: Nktm9tkQwWJqU24oj2+Ol53/KiFpC0qPVyNC1mEByJhA+O9XNIyu4fmeiMznkrOQqmJr6Px1hnCyysKLp4v5td0mq0RWEKh4COXDQhU3fXiThx/YCFdlljlMk/+P6f+vZ+HqMeWehM21nZd2YYIVi2tvZwk4yqs1s6OSE0uIBE5Gks5UwnVRCqhHozIgfy8NQ9am5pQUvrNLYWqGE07hkWBcu7AnoebsmkifZUgjsfISLa6krVO6I/W2d7Yan8Vh3i8cDhQTp8RGGyIOAclbJ5Tyu2uqGrgL5WSjDdySBtl/lufDc+SUEcIqyDwwVYYp6kkE7n19oN+rgDwx87pUq//xYJL0rIH9Ss6bdWYTPvixCQINn0GIlEUS2RNqzShbL+jpUSADgjldDpr+I8uUnnxZza02f+jCZdJr9yyT1Y9w6C8Q2omW1rtfJfKoUdNq3YzK7VFGgGFRWAUqCXhA2IlFHlCQvADDqzgF7ZYzzpkqNFNPASxAnExBeYoPUz+xhFCyUtUJvFQxQwh0v2VItD/5s0roJMjYTETmIU3LcZCY4rLZuLB0dE2lXhlsUxhFJKKlb3cMuNG9epnxdr7CqDBsxKz7CJGnzOYPXFx36/c5Z8uTSqyzcBFlIde9/jwBUx39LFvadUiUVknsK5lKym1dQf+g6lrWEppNsY+thIg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
